'use client';

import React from 'react';

export default function Home() {
  return (
      <div className="min-h-screen bg-slate-50 font-sans">
            {/* NAVIGATION */}
                  <nav className="sticky top-0 z-50 bg-white border-b border-slate-200 px-6 py-4 flex justify-between items-center shadow-sm">
                          <h1 className="text-xl font-black tracking-tighter text-blue-600">
                                    SHARM<span className="text-orange-500">EXPLORE</span>
                                            </h1>
                                                    <button className="bg-blue-600 text-white text-xs font-bold px-4 py-2 rounded-full active:scale-95 transition">
                                                              RESERVER
                                                                      </button>
                                                                            </nav>

                                                                                  {/* SECTION HERO */}
                                                                                        <header className="p-4">
                                                                                                <div className="relative h-64 w-full rounded-3xl overflow-hidden shadow-xl">
                                                                                                          <img 
                                                                                                                      src="https://images.unsplash.com" 
                                                                                                                                  alt="Mer Rouge" 
                                                                                                                                              className="w-full h-full object-cover"
                                                                                                                                                        />
                                                                                                                                                                  <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent flex flex-col justify-end p-6">
                                                                                                                                                                              <h2 className="text-white text-2xl font-extrabold leading-tight">
                                                                                                                                                                                            Découvrez la Mer Rouge
                                                                                                                                                                                                        </h2>
                                                                                                                                                                                                                    <p className="text-blue-200 text-sm">Les meilleures excursions à Sharm</p>
                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                            </header>

                                                                                                                                                                                                                                                  {/* CATALOGUE */}
                                                                                                                                                                                                                                                        <main className="px-4 pb-12">
                                                                                                                                                                                                                                                                <h3 className="text-lg font-bold text-slate-800 mb-6 px-2">Nos Excursions</h3>

                                                                                                                                                                                                                                                                        <div className="grid grid-cols-1 gap-6">
                                                                                                                                                                                                                                                                                  {/* Carte Safari */}
                                                                                                                                                                                                                                                                                            <div className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
                                                                                                                                                                                                                                                                                                        <img src="https://images.unsplash.com" className="h-40 w-full object-cover" alt="Safari" />
                                                                                                                                                                                                                                                                                                                    <div className="p-4 flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                  <h4 className="font-bold text-slate-900">Safari Quad</h4>
                                                                                                                                                                                                                                                                                                                                                                  <p className="text-slate-500 text-xs">Désert du Sinaï</p>
                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-blue-600 font-black text-lg">25$</span>
                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Carte Plongée */}
                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <img src="https://images.unsplash.com" className="h-40 w-full object-cover" alt="Plongée" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="p-4 flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h4 className="font-bold text-slate-900">Ras Mohammed VIP</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-slate-500 text-xs">Snorkeling & Lunch</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-blue-600 font-black text-lg">45$</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <footer className="text-center py-6 text-slate-400 text-[10px]">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            © 2024 SHARM EXPLORE - S21 EDITION
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        