'use client';

import React, { useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';

export default function Home() {
  const [excursions, setExcursions] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);

      useEffect(() => {
          const fetchTours = async () => {
                try {
                        // On récupère les données de la table 'excursions'
                                const { data, error } = await supabase.from('excursions').select('*');
                                        if (error) throw error;
                                                setExcursions(data || []);
                                                      } catch (err) {
                                                              console.error("Erreur de chargement :", err);
                                                                    } finally {
                                                                            setLoading(false);
                                                                                  }
                                                                                      };
                                                                                          fetchTours();
                                                                                            }, []);

                                                                                              return (
                                                                                                  <main className="min-h-screen bg-slate-50 p-6 font-sans">
                                                                                                        <h1 className="text-2xl font-black text-blue-600 mb-8 tracking-tighter">
                                                                                                                SHARM EXPLORE
                                                                                                                      </h1>

                                                                                                                            {loading ? (
                                                                                                                                    <div className="flex justify-center py-10">
                                                                                                                                              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
                                                                                                                                                      </div>
                                                                                                                                                            ) : (
                                                                                                                                                                    <div className="grid gap-6">
                                                                                                                                                                              {excursions.length > 0 ? (
                                                                                                                                                                                          excursions.map((tour) => (
                                                                                                                                                                                                        <div key={tour.id} className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
                                                                                                                                                                                                                        <img 
                                                                                                                                                                                                                                          src={tour.image_url || 'https://via.placeholder.com'} 
                                                                                                                                                                                                                                                            className="h-44 w-full object-cover" 
                                                                                                                                                                                                                                                                              alt={tour.title} 
                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                              <div className="p-4">
                                                                                                                                                                                                                                                                                                                                <div className="flex justify-between items-start mb-2">
                                                                                                                                                                                                                                                                                                                                                    <h3 className="font-bold text-lg text-slate-800">{tour.title}</h3>
                                                                                                                                                                                                                                                                                                                                                                        <span className="text-blue-600 font-black">{tour.price_adult}$</span>
                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-slate-500 text-sm mb-4 line-clamp-2">{tour.description}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                              <button className="w-full bg-blue-600 text-white py-3 rounded-xl font-bold active:scale-95 transition">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  Détails
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-center text-slate-400">Aucune excursion trouvée.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  