'use client';

import React, { useEffect, useState } from 'react';
// Correction Chemin : On utilise ../ pour sortir du dossier app vers lib
import { supabase } from '../lib/supabase'; 

export default function Home() {
  // Correction Type : On définit que c'est un tableau d'objets [any[]]
    const [excursions, setExcursions] = useState<any[]>([]);
      const [loading, setLoading] = useState(true);

        useEffect(() => {
            async function fetchTours() {
                  try {
                          const { data, error } = await supabase
                                    .from('excursions')
                                              .select('*');
                                                      
                                                              if (error) throw error;
                                                                      if (data) setExcursions(data);
                                                                            } catch (error) {
                                                                                    console.error('Erreur Supabase:', error);
                                                                                          } finally {
                                                                                                  setLoading(false);
                                                                                                        }
                                                                                                            }
                                                                                                                fetchTours();
                                                                                                                  }, []);

                                                                                                                    return (
                                                                                                                        <div className="min-h-screen bg-slate-50">
                                                                                                                              <nav className="p-6 bg-white border-b flex justify-between items-center">
                                                                                                                                      <h1 className="text-xl font-black text-blue-600 uppercase tracking-tighter">
                                                                                                                                                Sharm Explore
                                                                                                                                                        </h1>
                                                                                                                                                              </nav>

                                                                                                                                                                    <main className="p-6">
                                                                                                                                                                            {loading ? (
                                                                                                                                                                                      <div className="text-center py-10 text-slate-400">Chargement...</div>
                                                                                                                                                                                              ) : (
                                                                                                                                                                                                        <div className="grid grid-cols-1 gap-6">
                                                                                                                                                                                                                    {excursions.map((tour) => (
                                                                                                                                                                                                                                  <div key={tour.id} className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
                                                                                                                                                                                                                                                  <div className="h-44 relative">
                                                                                                                                                                                                                                                                    {/* Protection Image : On vérifie si l'URL existe */}
                                                                                                                                                                                                                                                                                      <img 
                                                                                                                                                                                                                                                                                                          src={tour.image_url || 'https://via.placeholder.com'} 
                                                                                                                                                                                                                                                                                                                              alt={tour.title} 
                                                                                                                                                                                                                                                                                                                                                  className="w-full h-full object-cover" 
                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                      <div className="absolute top-3 right-3 bg-blue-600 text-white px-3 py-1 rounded-full font-bold">
                                                                                                                                                                                                                                                                                                                                                                                                          {tour.price_adult}$
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="p-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3 className="font-bold text-lg text-slate-900">{tour.title}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-slate-500 text-sm mt-1">{tour.description}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button className="w-full mt-4 bg-blue-600 text-white py-3 rounded-xl font-bold active:bg-blue-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Réserver
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                